<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>name</key>
	<string>PageBout (JavaScript)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(//)(#dbg)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.punctuation.definition.comment.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>active.dbg.token.open.pagebout.comment.line.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(//)(\2)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.punctuation.definition.comment.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>active.dbg.token.close.pagebout.comment.line.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>area.dbg.marker.pagebout.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?=.*//#dbg\s*$)</string>
					<key>end</key>
					<string>(//)(#dbg)\s*$\n</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.punctuation.definition.comment.js</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>active.dbg.token.mark.pagebout.comment.line.js</string>
						</dict>
					</dict>
					<key>name</key>
					<string>active.dbg.marker.pagebout.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js.jquery</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js.jquery</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>inactive.dbg.line.pagebout.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.punctuation.definition.comment.js</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>inactive.dbg.token.mark.pagebout.comment.line.js</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(.*)\s*(//)(#dbg)\s*$</string>
			<key>name</key>
			<string>inactive.dbg.marker.pagebout.js</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=.*//#chk\s*$)</string>
			<key>end</key>
			<string>(//)(#chk)\s*$\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.punctuation.definition.comment.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>chk.token.mark.pagebout.comment.line.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>chk.marker.pagebout.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js.jquery</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.punctuation.definition.comment.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.require.pagebout.comment.line.js</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>path.require.pagebout.comment.line.js</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(//)\s*(require)\((.*?)\)\s*$\n</string>
			<key>name</key>
			<string>require.pagebout.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js.jquery</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.jquery.pagebout</string>
	<key>uuid</key>
	<string>30A6C507-34EB-47CC-A78D-A54EA47574F3</string>
</dict>
</plist>
